# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/91974/Downloads/Srp.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QWidget, QGraphicsDropShadowEffect
from qfluentwidgets import FluentIcon as FIF

from app.view.ui.ui_rte_interface import Ui_Frame as UiRteInterface


class RteInterface(UiRteInterface, QWidget):
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.setupUi(self)

        self.PushButton.setIcon(FIF.FOLDER)
        self.PushButton_2.setIcon(FIF.FOLDER)

        # add shadow effect to card
        self.setShadowEffect(self.CardWidget)

    def setShadowEffect(self, card: QWidget):
        shadowEffect = QGraphicsDropShadowEffect(self)
        shadowEffect.setColor(QColor(0, 0, 0, 15))
        shadowEffect.setBlurRadius(10)
        shadowEffect.setOffset(0, 0)
        card.setGraphicsEffect(shadowEffect)
