# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Github/FastX-Gui/app/view/ui/ui_func_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import qfluentwidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1298, 1740)
        self.CardWidget = CardWidget(Form)
        self.CardWidget.setGeometry(QtCore.QRect(10, 10, 1281, 381))
        self.CardWidget.setObjectName("CardWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
from qfluentwidgets import CardWidget
