# Generated by dev.py on 2026-03-03 16:29:37
# DO NOT EDIT MANUALLY

# 源文件
SOURCES += app\card\autoplot_setting_card.py \
            app\card\enhance_table_widget.py \
            app\card\messagebox_custom.py \
            app\card\public_card.py \
            app\common\background_manager.py \
            app\common\config.py \
            app\common\icon.py \
            app\common\license_service.py \
            app\common\notification.py \
            app\common\resource.py \
            app\common\setting.py \
            app\common\signal_bus.py \
            app\common\style_sheet.py \
            app\common\translator.py \
            app\common\trie.py \
            app\common\utils.py \
            app\common\web.py \
            app\components\card_example.py \
            app\components\config_card.py \
            app\components\custom_titlebar.py \
            app\components\info_card.py \
            app\components\link_card.py \
            app\components\main_layout_card.py \
            app\components\pivot.py \
            app\components\statistic_widget.py \
            app\tools\core\qc_composition_core.py \
            app\tools\core\rm_comments_core.py \
            app\tools\ui\ComGroupMapping_ui.py \
            app\tools\ui\FastCCP_ui.py \
            app\tools\ui\FastDem_ui.py \
            app\tools\ui\FastE2E_ui.py \
            app\tools\ui\FastFaultManager_ui.py \
            app\tools\ui\FastSomeIp_ui.py \
            app\tools\ui\qc_composition_ui.py \
            app\tools\ui\rm_comments_ui.py \
            app\view\app_interface.py \
            app\view\floating_window\levitation.py \
            app\view\floating_window\process_center.py \
            app\view\func_interface.py \
            app\view\home_interface.py \
            app\view\library_interface.py \
            app\view\log_interface.py \
            app\view\main_window.py \
            app\view\register_window.py \
            app\view\setting_interface.py \
            app\view\tool_interface.py \
            app\zbWidgetLib\base\base.py \
            app\zbWidgetLib\base\hook.py \
            app\zbWidgetLib\base\icon.py \
            app\zbWidgetLib\components\button.py \
            app\zbWidgetLib\components\card.py \
            app\zbWidgetLib\components\file_chooser.py \
            app\zbWidgetLib\components\flyout.py \
            app\zbWidgetLib\components\image.py \
            app\zbWidgetLib\components\info_badge.py \
            app\zbWidgetLib\components\loading.py \
            app\zbWidgetLib\components\page.py \
            app\zbWidgetLib\components\progress.py \
            app\zbWidgetLib\components\scroll.py \
            app\zbWidgetLib\components\splash_screen.py \
            app\zbWidgetLib\components\widget.py \
            app\zbWidgetLib\components\window.py \
            dev.py \
            main.py

# 翻译文件
TRANSLATIONS += app\resource\i18n\app.zh_CN.ts \
                app\resource\i18n\app.zh_HK.ts

# 编码设置
CODECFORTR = UTF-8

# 禁止生成临时文件
QMAKE_EXTRA_TARGETS += no_temp_files
